name: Terraform Deploy on Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: ğŸ“¦ Checkout repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Verify Terraform installed
        run: terraform -version

      - name: ğŸ§© Terraform Init
        working-directory: infra/infra/terraform
        run: terraform init

      - name: âœ… Terraform Validate
        working-directory: infra/infra/terraform
        run: terraform validate

      - name: ğŸ§  Terraform Plan
        working-directory: infra/infra/terraform
        run: terraform plan -out=tfplan

      - name: ğŸš€ Terraform Apply
        working-directory: infra/infra/terraform
        run: terraform apply -auto-approve
